force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event Speaker  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SpeakerRegistration.cls
public class SpeakerRegistration{
    public Speaker__c speaker{get;set;}
    public Event_Speaker__c eventSpeaker{get;set;}
    public SpeakerRegistration(){
        speaker=new Speaker__c();
        eventSpeaker=new Event_Speaker__c();
    }
    public void save(){
        try{
            insert speaker;
            eventSpeaker.Speaker__c=speaker.Id;
            insert eventSpeaker;
            speaker= new Speaker__c();
            eventSpeaker=new Event_Speaker__c();


        }
        catch(Exception e){
            System.debug(e.getMessage());
        }
    }
}