force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event   Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventRegistrationController.cls
public class EventRegistrationController {
    public Event_Organizer__c eorganizer{get;set;}
    public Event__c event{get;set;}
    public Location__c location{get;set;}
    public EventRegistrationController(){
        eorganizer= new Event_Organizer__c();
        event= new Event__c();
        location=new Location__c();

    }
    public void addEventOrganizer(){
        try{
         insert location;
         event.Organizer__c=eorganizer.Id;
         insert eorganizer;
         if(event.Event_Type__c!='virtual')
         event.location__c=location.Id;
         insert event;
         eorganizer= new Event_Organizer__c();
         event= new Event__c();
         location = new Location__c();


        }
        catch(Exception e){
            System.debug(e.getMessage());
        }
    }


}